version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: piacct-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pi_user
      MONGO_INITDB_ROOT_PASSWORD: pi_password
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: piacct-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MONGO_HOST: mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: piacct-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env.development
    ports:
      - "3314:80"
    depends_on:
      - backend

  reverse-proxy:
    build: ./reverse-proxy
    container_name: piacct-proxy
    restart: unless-stopped
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
